# Generated by Django 5.1.3 on 2024-12-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_of_publication']},
        ),
    ]
